### ISSUE TITLE
predicting on unseen data in chapter 2

### ISSUE THREAD

**Issue by hima111997** [Apress/artificial-neural-networks-with-tensorflow-2#7]
customer = model.predict([[615, 1, 22, 5, 20000, 5, 1, 1, 60000, 0, 0]])
should not the values in this line of code be scaled using the StandardScaler before using them in prediction?

**Comment by ABCOM2000** [comment]
Since this code appears in chapter2, I kept the data processing at minimal. The later chapters cover the data pre-processing fully.

**Comment by hima111997** [comment]
okay thank you
