### ISSUE TITLE
A question about transfer learning Ch4

### ISSUE THREAD

**Issue by hima111997** [Apress/artificial-neural-networks-with-tensorflow-2#8]
Hello sir,

I have a question related to the transfer learning mentioned in Ch4.
in the book you downloaded a model from tensorflow hub for prediction, however, I saw some people using the models in tf.keras.applications.
So is there a difference between the two ways?

Thanks

**Comment by profsarang** [comment]
The tf.keras.applications contain pre-trained models which work with TF1.x. 

https://tfhub.dev/google/tf2-preview/mobilenet_v2/classification/4"
 
As you see in the above URL, the updated models are put in /tf2-preview/ folder. This model works in any TF2 project

**Comment by hima111997** [comment]
You mean the models in TF.Keras.applications work with both tf1 and tf2 but the modrks in the Hub work with tf2 only?

Sent from Yahoo Mail on Android 
 
  On الأحد, يوليو ٢٥, ٢٠٢١ at ٢:١٥ م, ***@***.***> wrote:   

The tf.keras.applications contain pre-trained models which work with TF1.x. 

https://tfhub.dev/google/tf2-preview/mobilenet_v2/classification/4"
 
As you see in the above URL, the updated models are put in /tf2-preview/ folder. This model works in any TF2 project

**Comment by profsarang** [comment]
No, you did not get it right. Look at the attached screenshot. It says that this VGG16 module requires TensorFlow 1 version.

**Comment by hima111997** [comment]
Sorry for inconvenience but I can't see the screenshot (maybe because I am seeing it from the mobile). If it is from the tensorflow website, could you please send the link itself?

**Comment by profsarang** [comment]
Just check the TF documentation

**Comment by hima111997** [comment]
i checked the documentations and this is the image i found.

![image](https://user-images.githubusercontent.com/55895327/126905517-312b5d93-cf7c-4e86-9a7f-d522f571bf31.png)

when i clicked on tensorflow 1 version

this is what appeared

![image](https://user-images.githubusercontent.com/55895327/126905566-7b7a8fc1-ec11-4e08-b716-811cc7fe13db.png)

please note the version number in both images

![image](https://user-images.githubusercontent.com/55895327/126905592-98c11262-bc75-4257-abd7-90dd0fe38239.png)

![image](https://user-images.githubusercontent.com/55895327/126905631-48d7a6e5-43f5-4b00-ba46-efb3148382cf.png)

so i think there are two versions for VGG 16 one for each tensorflow version

**Comment by profsarang** [comment]
When I wrote the chapter, TF2 version was not available. Thanks for bringing it to my notice. You may use this (tf.keras.applications) rather than the one from tfhub - anyway, tfhub version was probably only for experimental purposes.

**Comment by hima111997** [comment]
Okay thanks you

Sent from Yahoo Mail on Android 
 
  On الاثنين, يوليو ٢٦, ٢٠٢١ at ٦:٠٥ ص, ***@***.***> wrote:   

When I wrote the chapter, TF2 version was not available. Thanks for bringing it to my notice. You may use this (tf.keras.applications) rather than the one from tfhub - anyway, tfhub version was probably only for experimental purposes.
